### ISSUE TITLE
Version 1.1.2 doesn't work on Ubuntu 20.04

### ISSUE THREAD

**Issue by funkycram** [brrd/abricotine#318]
Version 1.0.0 works well, but version 1.1.2 doesn't work on Ubuntu 20.04.

Error message:
```
Gtk-Message: 17:39:58.078: Failed to load module "unity-gtk-module"
Gtk-Message: 17:39:58.079: Failed to load module "unity-gtk-module"
libva error: /usr/lib/x86_64-linux-gnu/dri/iHD_drv_video.so init failed
[261760:0522/173958.199909:ERROR:sandbox_linux.cc(377)] InitializeSandbox() called with multiple threads in process gpu-process.
[
  [Error: ENOENT: no such file or directory, lstat '/opt/Abricotine/resources/app.asar.unpacked/default/dictionaries'] {
    errno: -2,
    code: 'ENOENT',
    syscall: 'lstat',
    path: '/opt/Abricotine/resources/app.asar.unpacked/default/dictionaries'
  }
]
```

Then, if I press CRTL + C:
![image](https://user-images.githubusercontent.com/23310825/169703911-2124439d-ab7d-4f9e-b17c-a4cc34162692.png)

Thanks for this great app!

**Comment by kkasra12** [comment]
I have a similar problem with version 1.1.2
the error is:
```bash
$ abricotine 
[
  [Error: ENOENT: no such file or directory, lstat '/opt/Abricotine/resources/app.asar.unpacked/default/dictionaries'] {
    errno: -2,
    code: 'ENOENT',
    syscall: 'lstat',
    path: '/opt/Abricotine/resources/app.asar.unpacked/default/dictionaries'
  }
]
[
  [Error: ENOENT: no such file or directory, lstat '/opt/Abricotine/resources/app.asar.unpacked/default/lang'] {
    errno: -2,
    code: 'ENOENT',
    syscall: 'lstat',
    path: '/opt/Abricotine/resources/app.asar.unpacked/default/lang'
  }
]
[
  [Error: ENOENT: no such file or directory, lstat '/opt/Abricotine/resources/app.asar.unpacked/default/templates'] {
    errno: -2,
    code: 'ENOENT',
    syscall: 'lstat',
    path: '/opt/Abricotine/resources/app.asar.unpacked/default/templates'
  }
]
[
  [Error: ENOENT: no such file or directory, lstat '/opt/Abricotine/resources/app.asar.unpacked/default/themes'] {
    errno: -2,
    code: 'ENOENT',
    syscall: 'lstat',
    path: '/opt/Abricotine/resources/app.asar.unpacked/default/themes'
  }
]
```

Here is some more results:
```bash
$ ls /opt/Abricotine/resources/app.asar.unpacked/default/themes
ls: cannot access '/opt/Abricotine/resources/app.asar.unpacked/default/themes': No such file or directory
$ ls /opt/Abricotine/resources/app.asar.unpacked/default/
ls: cannot access '/opt/Abricotine/resources/app.asar.unpacked/default/': No such file or directory
$ ls /opt/Abricotine/resources/app.asar.unpacked/
ls: cannot access '/opt/Abricotine/resources/app.asar.unpacked/': No such file or directory
$ ls /opt/Abricotine/resources
app.asar
$ ls -l /opt/Abricotine/resources
total 45912
-rw-r--r-- 1 root root 47011579 May 22 17:51 app.asar
```

**Comment by brrd** [comment]
@funkycram @kkasra12 Thanks for your feedback.

Can you please try to run `abricotine --reset` in your terminal?

**Comment by funkycram** [comment]
Same problem, even after `sudo apt remove --purge abricotine` and reinstall.

```
$ abricotine --reset
Gtk-Message: 09:54:43.497: Failed to load module "unity-gtk-module"
Gtk-Message: 09:54:43.499: Failed to load module "unity-gtk-module"
[
  [Error: ENOENT: no such file or directory, lstat '/opt/Abricotine/resources/app.asar.unpacked/default/dictionaries'] {
    errno: -2,
    code: 'ENOENT',
    syscall: 'lstat',
    path: '/opt/Abricotine/resources/app.asar.unpacked/default/dictionaries'
  }
]
[
  [Error: ENOENT: no such file or directory, lstat '/opt/Abricotine/resources/app.asar.unpacked/default/lang'] {
    errno: -2,
    code: 'ENOENT',
    syscall: 'lstat',
    path: '/opt/Abricotine/resources/app.asar.unpacked/default/lang'
  }
]
[
  [Error: ENOENT: no such file or directory, lstat '/opt/Abricotine/resources/app.asar.unpacked/default/templates'] {
    errno: -2,
    code: 'ENOENT',
    syscall: 'lstat',
    path: '/opt/Abricotine/resources/app.asar.unpacked/default/templates'
  }
]
[
  [Error: ENOENT: no such file or directory, lstat '/opt/Abricotine/resources/app.asar.unpacked/default/themes'] {
    errno: -2,
    code: 'ENOENT',
    syscall: 'lstat',
    path: '/opt/Abricotine/resources/app.asar.unpacked/default/themes'
  }
]
libva error: /usr/lib/x86_64-linux-gnu/dri/iHD_drv_video.so init failed
[346752:0524/095443.701457:ERROR:sandbox_linux.cc(377)] InitializeSandbox() called with multiple threads in process gpu-process.
```

When I reinstall version 1.0.0 it works well.
Thanks.

PS: je viens de voir que t'es Français, moi je suis à Toulouse ! Merci pour le débogage et surtout cet excellent éditeur markdown !

**Comment by brrd** [comment]
OK, I will have a look at this when I have some time.

Merci ;-)

**Comment by tech189** [comment]
Just to let you know, I get the same error on Windows 11 with version 1.1.2, the same directories cannot be found: `...\resources\app.asar.unpacked\default\dictionaries, lang, templates, themes`. The directory `app.asar.unpacked` doesn't exist at all. Also, the command `abricotine --reset` doesn't help sadly.

**Comment by brrd** [comment]
So it's not only happening on Linux. It's probably an issue when reading into the asar archive. 
Your comment is very helpful @tech189, thank you.

**Comment by brrd** [comment]
I think this was fixed in [version 1.1.3](https://github.com/brrd/abricotine/releases/tag/v1.1.3).

**Comment by funkycram** [comment]
Thanks a lot!
Unfortunately, I still cannot make it work.
Tested:
- `sudo apt remove --purge abricotine`
- Installed v 1.1.3

I get:
```
$ abricotine 
Gtk-Message: 15:09:16.569: Failed to load module "unity-gtk-module"
Gtk-Message: 15:09:16.570: Failed to load module "unity-gtk-module"
libva error: /usr/lib/x86_64-linux-gnu/dri/iHD_drv_video.so init failed
[384711:0524/150916.656234:ERROR:sandbox_linux.cc(377)] InitializeSandbox() called with multiple threads in process gpu-process.
Error while loading localization data: Error: EACCES: permission denied, open '/home/marc/.config/Abricotine/app/lang/en.json'
```

![image](https://user-images.githubusercontent.com/23310825/170042636-6b084d2e-6fe7-4536-bdd4-edba33152d63.png)

Then, with --reset:

```
$ abricotine --reset
Gtk-Message: 15:10:49.884: Failed to load module "unity-gtk-module"
Gtk-Message: 15:10:49.885: Failed to load module "unity-gtk-module"
libva error: /usr/lib/x86_64-linux-gnu/dri/iHD_drv_video.so init failed
[384861:0524/151049.976340:ERROR:sandbox_linux.cc(377)] InitializeSandbox() called with multiple threads in process gpu-process.
[
  [Error: EACCES: permission denied, unlink '/home/marc/.config/Abricotine/app/templates/default/template.html'] {
    errno: -13,
    code: 'EACCES',
    syscall: 'unlink',
    path: '/home/marc/.config/Abricotine/app/templates/default/template.html'
  }
]
```

If I press CTRL + C:
![image](https://user-images.githubusercontent.com/23310825/170043012-5a922029-3dde-4dfd-bcc8-985fc4dbb37f.png)

On of the problem seems to be here:
```
$ ls -lah /home/marc/.config/Abricotine/app/templates/
ls: cannot access '/home/marc/.config/Abricotine/app/templates/.': Permission denied
ls: cannot access '/home/marc/.config/Abricotine/app/templates/..': Permission denied
total 0
d????????? ? ? ? ?              ? .
d????????? ? ? ? ?              ? ..
```

Then, I did try this:
```
$ rm -rf /home/marc/.config/Abricotine/app/templates/
$ ls -lah /home/marc/.config/Abricotine/app/templates/
ls: cannot access '/home/marc/.config/Abricotine/app/templates/': No such file or directory
$ mkdir /home/marc/.config/Abricotine/app/templates/
$ ls -lah /home/marc/.config/Abricotine/app/templates/
total 8,0K
drwxrwxr-x 2 marc marc 4,0K mai   24 15:16 .
drwxrwxr-x 6 marc marc 4,0K mai   24 15:16 ..
```

So the folder `.config/Abricotine/app/templates/` is now OK.
But if I start do again `abricotine --reset` then I have the same problem:

```
$ ls -lah /home/marc/.config/Abricotine/app/templates/
ls: cannot access '/home/marc/.config/Abricotine/app/templates/.': Permission denied
ls: cannot access '/home/marc/.config/Abricotine/app/templates/..': Permission denied
total 0
d????????? ? ? ? ?              ? .
d????????? ? ? ? ?              ? ..
```

**Comment by brrd** [comment]
@funkycram I think this is another issue.

Can you please try `rm -rf /home/marc/.config/Abricotine`?

**Comment by funkycram** [comment]
> @funkycram I think this is another issue.
> 
> Can you please try `rm -rf /home/marc/.config/Abricotine`?

Yes, I did, same problem.

**Comment by maxtat3** [comment]
Exactly the same problem after install as @funkycram describes. Tested on Ubuntu 18.04 with LXDE environment.

**Comment by brrd** [comment]
I'm planning to fix this bug as a priority, as soon as I find enough time to work on it.

**Comment by brrd** [comment]
Can you please try https://github.com/brrd/abricotine/releases/tag/v1.1.4 and confirm it fixed the issue?

**Comment by funkycram** [comment]
It works fine, thanks a lot! 😊

For informations for others, I don't know if it's necessary, but I did, after installing:
```
rm -rf ~/.config/Abricotine
abricotine --reset
```

**Comment by maxtat3** [comment]
Tested. Also version 1.1.4 works great. Thanks a lot for the quick fix !
