### ISSUE TITLE
German spell checker

### ISSUE THREAD

**Issue by lukas-h** [brrd/Abricotine#4]
If letters with diacritical marks (like ä, ö, ü, á, è) are in words, the spell checker says, that the word has some spelling mistakes ( red jagged underline ). I think it is not only this, it looks like Abricotine does generally not support UTF-8? Are there any plans to support it in the feature?

Except this, it works very fine

**Comment by brrd** [comment]
Abricotine does support UTF-8 but you pointed out the bad encoding of several dictionaries. I just fixed it on the develop branch so it should work with the next release.

Since the dictionaries are copied to the app config folder when Abricotine is lauched for the first time, you will need to fix it manually on your computer by replacing the old dicts. You can copy [this new dict folder](https://github.com/brrd/Abricotine/tree/develop/default/dict) in your Abricotine config dir, it should do the work. I'll try to think about an easier way for updating this.

**Comment by lukas-h** [comment]
Thank you :+1:

**Comment by yajo10** [comment]
I installed this application freshly just a few weeks ago (version 1.0.0) and I still have this issue on linux (Ubuntu). 
Is there any thing I can do to debug this? 

Everything else is just working fine! Thank's for this great app!

**Comment by FireFragment** [comment]
Brrd said:
> I just fixed it on the develop branch so it **should work with the next release**.

It will work.

**Comment by brrd** [comment]
@yajo10 Does this happen with German dictonary only? Can you provide examples?

**Comment by yajo10** [comment]
For example with the text token from [here](https://lingua.com/german/reading/vorstellung/)

I tried it with different texts from other languages. For french all glyphs and so are working quite well. And in German everything except "äöüß" is working.

I just checked the de_DE.dict file in the app/dict/de_DE/ directory, there are the correct words in the file.

Maybe it's worth to mention that I'm using ubuntu 20.04 and installed abricotine via the .deb file.

I tried to build the abricotine from source code. But at the moment I'm stuck at building hunspell. There something does not work.
